# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6467750df974f977368121ef6530a52be448189a0f15e2df851ae1425e770f9c24964f1186111efc1e9f2af9fd0e623f1ef3a81abb2665bc9b6ede7a66e664fa

test:
  secret_key_base: 5e056c65b81ff4e2d5d3fae68703ae09e471d4a6b38359fb635762c37d5ef35f6a5b9a3a3ce7ffd2bae898a25a49d5481f0d33180271b1a222dfb16e7d824340

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
